# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Use GitHub source instead of CDN to avoid 500 errors
source 'https://github.com/CocoaPods/Specs.git'

# CocoaPods will auto-generate the rest via Flutter

